spring:
  datasource:
#    url: jdbc:postgresql://db-pet:5432/pets
    url: jdbc:postgresql://localhost:5432/pets
    username: pet
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
#    host: rabbit
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082
